# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ig < Formula
  desc "invitation images generator."
  homepage "https://github.com/jiy1012/invitationGenerator"
  version "0.1.3"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jiy1012/invitationGenerator/releases/download/v0.1.3/ig_Darwin_arm64.tar.gz"
      sha256 "3004c849590637100518346b78b3ee10933b552e5743f984295c060206ca7c05"

      def install
        bin.install "ig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jiy1012/invitationGenerator/releases/download/v0.1.3/ig_Darwin_x86_64.tar.gz"
      sha256 "d3ed8e2f136852b61c0a4083d14d82f747eee628334c42cfd556315e244cd0d2"

      def install
        bin.install "ig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jiy1012/invitationGenerator/releases/download/v0.1.3/ig_Linux_arm64.tar.gz"
      sha256 "9c77e9e25fc31b3b16bac3d6b71af27dd0bab8b12dd9543e858c4cea4f78b17c"

      def install
        bin.install "ig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jiy1012/invitationGenerator/releases/download/v0.1.3/ig_Linux_x86_64.tar.gz"
      sha256 "1697e8d0bfac72adc833aafd3e63a6abef381901374aa06e906b800b76b223d3"

      def install
        bin.install "ig"
      end
    end
  end

  test do
    system "#{bin}/ig --help"
  end
end
