# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ig < Formula
  desc "invitation images generator."
  homepage "https://github.com/jiy1012/invitationGenerator"
  version "0.1.5"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jiy1012/invitationGenerator/releases/download/v0.1.5/ig_Darwin_arm64.tar.gz"
      sha256 "57a2b69dd5c47d9b6398f324fdd8f250cacd41bf82a107a8d5a7090ffb9ee889"

      def install
        bin.install "ig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jiy1012/invitationGenerator/releases/download/v0.1.5/ig_Darwin_x86_64.tar.gz"
      sha256 "f924cf98c85b8786504227a93b46f19c19628e4fa19e1fd83be8bc31a843a0fb"

      def install
        bin.install "ig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jiy1012/invitationGenerator/releases/download/v0.1.5/ig_Linux_arm64.tar.gz"
      sha256 "1110353f574d52083792923d591dae3a3d3517da2e08f32d3c2b239138998c3c"

      def install
        bin.install "ig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jiy1012/invitationGenerator/releases/download/v0.1.5/ig_Linux_x86_64.tar.gz"
      sha256 "8baf5a209dcf15b88f80d603ec9b483031fb08a14bf0f3034d21ff608db4a54f"

      def install
        bin.install "ig"
      end
    end
  end

  test do
    system "#{bin}/ig --help"
  end
end
